version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: vsce
    versions:
    - 1.84.0
    - 1.85.0
    - 1.85.1
    - 1.86.0
    - 1.87.0
  - dependency-name: typescript
    versions:
    - 3.9.9
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: chalk
    versions:
    - 4.1.0
